#%RAML 1.0 DataType
displayName: Show Metrics Response
description: Data type for Show Metrics Response
additionalProperties: true
type: object
properties:
  message:
    description: Response of update workers calls
    type: string
    required: true
    example: "Updated Successfully!"
