#%RAML 1.0 DataType
displayName: Update Workers Response
description: Data type to update workers Response
additionalProperties: true
type: object
properties:
  message:
    description: Response of update workers calls
    type: string
    required: true
    example: "Updated Successfully!"
