#%RAML 1.0
title: vCores Management
mediaType:
  - application/json
version: 1.0.0
protocols:
  - HTTPS
  - HTTP
types:
  updateWorkers: !include dataTypes/updateWorkers.raml
  updateWorkersResponse: !include dataTypes/updateWorkersResponse.raml
  showMetrics: !include dataTypes/showMetrics.raml
  showMetricsResponse: !include dataTypes/showMetricsResponse.raml
/list-apps:
  get:
    queryParameters:
      Environment:
        example: SIT
        type: string
    responses:
      "200":
        body:
          application/json:
            description: Get the list of applications with worker details
            example: !include examples/listAppsResponse.json
            type: object
/list-environments:
  get:
    responses:
      "200":
        body:
          application/json:
            description: Get the list of environments
            example: !include examples/listEnvsResponse.json
            type: object            
/update-workers:
  post:
    body:
      application/json:
        type: updateWorkers
        description: payload for update workers
        example: !include examples/updateWorkers.json
    responses:
      "200":
        body:
          application/json:
            description: Get the list of applications with worker details
            example: !include examples/updateWorkersResponse.json
            type: updateWorkersResponse            
                     
/show-metrics:
  post:
    body:
      application/json:
        type: showMetrics
        description: payload for show-metrics
       
    responses:
      "200":
        body:
          application/json:
            description: Display the cpu and memory metrics
            
            type: updateWorkersResponse    
                      